<a href="https://colab.research.google.com/github/akashf/DataScience-Notes/blob/master/Prediction_using_forward_propagation_Method_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is first notbook for Artifical Intelligence technique Forwarod Propagation :


all deep learning libraries have the entire training and prediction processes implemented, and so in practice you wouldn't really need to build a neural network from scratch.

**How a neural network** makes predictions through the forward propagation process. Here is a neural network that takes two inputs, has one hidden layer with two nodes, and an output layer with one node.
![Neueal Network Forward Propagation Calculation Technique ](http://cocl.us/neural_network_example)

X, is the input value
W, is the weight of the input x
b, is the bias like constent we add 


### **Bias is like the intercept** 
added in a linear equation. It is an additional parameter in the Neural Network which is used to adjust the output along with the weighted sum of the inputs to the neuron. Thus, Bias is a constant which helps the model in a way that it can fit best for the given data.

Let's start by randomly initializing the weights and the biases in the network. We have 6 weights and 3 biases, one for each node in the hidden layer as well as for each node in the output layer.

In [0]:
import numpy as np
weights = np.around(np.random.uniform(size = 6), decimals = 2)
biases = np.around(np.random.uniform(size = 3), decimals = 2)

Printing the weights and biases

In [5]:
print(weights)
print(biases)

[0.93 0.63 0.38 0.81 0.69 0.51]
[0.95 0.12 0.12]


Now that we have the weights and the biases defined for the network, let's compute the output for a given input, $x_1$ and $x_2$.

In [6]:
x1 = 0.5
x2 = 0.84
print('x1 is {} and x2 is {}'.format(x1,x2))

x1 is 0.5 and x2 is 0.84


Let's start by computing the wighted sum of the inputs, $z_{1, 1}$, at the first node of the hidden layer.

In [7]:

z_11 = x1*weights[0]+x2*weights[1]+biases[0]
print('The weighted sum of the inputs at the first node in the hidden layer is {}'.format(np.around(z_11, decimals = 4)))

The weighted sum of the inputs at the first node in the hidden layer is 1.9442








Next, let's compute the weighted sum of the inputs, $z_{1, 2}$, at the second node of the hidden layer. Assign the value to **z_12**.

In [8]:
z_12 = x1*weights[2]+x2*weights[3]+ biases[1]
print('The weighted sum of the inputs at the second node in hidden layer is {}'.format(np.around(z_12, decimals = 4)))

The weighted sum of the inputs at the second node in hidden layer is 0.9904


Next, assuming a sigmoid activation function, let's compute the activation of the first node, $a_{1, 1}$, in the hidden layer.

In [9]:
a11 = 1.0/(1.0+(np.exp(-z_11)))
a11
print('The Activation Funciton of First node of hidden layer A11 is {}: '.format(np.around(a11, decimals=4)))

The Activation Funciton of First node of hidden layer A11 is 0.8748: 


In [10]:
a12 = 1.0/(1.0+(np.exp(-z_12)))
print('The Activation Funciton of Second node of hidden layer A12 is {}: '.format(np.around(a12, decimals=4)))

The Activation Funciton of Second node of hidden layer A12 is 0.7292: 



Now these activations will serve as the inputs to the output layer. So, let's compute the weighted sum of these inputs to the node in the output layer. Assign the value to **z_2**.

In [11]:
z_2 = a11*weights[4]+x2*weights[5]+biases[2]
print('The weighted sum of the output at the last node in the output  layer is {}'.format(np.around(z_2, decimals = 4)))


The weighted sum of the output at the last node in the output  layer is 1.152


Finally, let's compute the output of the network as the activation of the node in the output layer. Assign the value to **a_2**.

In [12]:
a_2 = 1.0/(1.0+(np.exp(-z_2)))
print('The Activation Funciton of Last node of output layer A12 is {}: '.format(np.around(a_2, decimals=4)))

The Activation Funciton of Last node of output layer A12 is 0.7599: 


<hr>

Obviously, neural networks for real problems are composed of many hidden layers and many more nodes in each layer. So, we can't continue making predictions using this very inefficient approach of computing the weighted sum at each node and the activation of each node manually. 

In order to code an automatic way of making predictions, let's generalize our network. A general network would take $n$ inputs, would have many hidden layers, each hidden layer having $m$ nodes, and would have an output layer. Although the network is showing one hidden layer, but we will code the network to have many hidden layers. Similarly, although the network shows an output layer with one node, we will code the network to have more than one node in the output layer.


<img src="http://cocl.us/general_neural_network" alt="Neural Network General" width=600px>

## Initialize a Network
<br>
Let's start by formally defining the structure of the network.

In [0]:
n = 2 # Number of input layers
num_hidden_layer = 2 # Number of hidden layer
m = [2,2] # Nodes in each hidden layer
num_output_layer = 1 #Number of output layer


Now that we defined the structure of the network, let's go ahead and inititailize the weights and the biases in the network to random numbers. In order to be able to initialize the weights and the biases to random numbers, we will need to import the **Numpy** library.

In [19]:
import numpy as np
num_nodes_previous = 0 #number of nodes in previous layer
network = {} #Initializing network as empty direcotry
#looping through each layer to initialize weights and biase to each layer 
#adding one to hidden layer in order to include output layer
for layer in range(num_hidden_layer+1):
  if layer == num_hidden_layer:
    layer_name = 'output'
    num_nodes = num_output_layer
  else:
    layer_name = 'layer_{}'.format(layer+1)
    num_nodes = m[layer]

    network[layer_name] = {}
    for node in range(num_nodes):
        node_name = 'node_{}'.format(node+1)
        network[layer_name][node_name] = {
            'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
            'bias': np.around(np.random.uniform(size=1), decimals=2),
        }
    
    num_nodes_previous = num_nodes
    
print(network) # print network



{'layer_1': {'node_1': {'weights': array([], dtype=float64), 'bias': array([0.72])}, 'node_2': {'weights': array([], dtype=float64), 'bias': array([0.29])}}, 'layer_2': {'node_1': {'weights': array([0.46, 0.6 ]), 'bias': array([0.92])}, 'node_2': {'weights': array([0.  , 0.84]), 'bias': array([0.87])}}}


Awesome! So now with the above code, we are able to initialize the weights and the biases pertaining to any network of any number of hidden layers and number of nodes in each layer. But let's put this code in a function so that we are able to repetitively execute all this code whenever we want to construct a neural network.


In [0]:
def initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output):
    
    num_nodes_previous = num_inputs # number of nodes in the previous layer

    network = {}
    
    # loop through each layer and randomly initialize the weights and biases associated with each layer
    for layer in range(num_hidden_layers + 1):
        
        if layer == num_hidden_layers:
            layer_name = 'output' # name last layer in the network output
            num_nodes = num_nodes_output
        else:
            layer_name = 'layer_{}'.format(layer + 1) # otherwise give the layer a number
            num_nodes = num_nodes_hidden[layer] 
        
        # initialize weights and bias for each /node
        network[layer_name] = {}
        for node in range(num_nodes):
            node_name = 'node_{}'.format(node+1)
            network[layer_name][node_name] = {
                'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
                'bias': np.around(np.random.uniform(size=1), decimals=2),
            }
    
        num_nodes_previous = num_nodes

    return network # return the network

## Compute Weighted Sum at Each Node
<br>
The weighted sum at each node is computed as the dot product of the inputs and the weights plus the bias. So let's create a function called *compute_weighted_sum* that does just that.



In [0]:
small_network = initialize_network(5, 3, [3, 2, 3], 1)

In [0]:
def compute_weighted_sum(inputs, weights, bias):
    return np.sum(inputs * weights) + bias

In [28]:
from random import seed
import numpy as np

np.random.seed(12)
inputs = np.around(np.random.uniform(size=5), decimals=2)

print('The inputs to the network are {}'.format(inputs))

The inputs to the network are [0.15 0.74 0.26 0.53 0.01]


In [29]:
node_weights = small_network['layer_1']['node_1']['weights']
node_bias = small_network['layer_1']['node_1']['bias']

weighted_sum = compute_weighted_sum(inputs, node_weights, node_bias)
print('The weighted sum at the first node in the hidden layer is {}'.format(np.around(weighted_sum[0], decimals=4)))


The weighted sum at the first node in the hidden layer is 1.602


## Compute Node Activation
<br>
Recall that the output of each node is simply a non-linear tranformation of the weighted sum. We use activation functions for this mapping. Let's use the sigmoid function as the activation function here. So let's define a function that takes a weighted sum as input and returns the non-linear transformation of the input using the sigmoid function.

In [0]:
def node_activation(weighted_sum):
    return 1.0 / (1.0 + np.exp(-1 * weighted_sum))

In [31]:
activaition_fn = node_activation(weighted_sum)
activaition_fn

array([0.83229773])

## Forward Propagation
<br>
The way we are going to accomplish this is through the following procedure:

1. Start with the input layer as the input to the first hidden layer.
2. Compute the weighted sum at the nodes of the current layer.
3. Compute the output of the nodes of the current layer.
4. Set the output of the current layer to be the input to the next layer.
5. Move to the next layer in the network.
5. Repeat steps 2 - 4 until we compute the output of the output layer.

In [0]:
def forward_propagate(network, inputs):
    
    layer_inputs = list(inputs) # start with the input layer as the input to the first hidden layer
    
    for layer in network:
        
        layer_data = network[layer]
        
        layer_outputs = [] 
        for layer_node in layer_data:
        
            node_data = layer_data[layer_node]
        
            # compute the weighted sum and the output of each node at the same time 
            node_output = node_activation(compute_weighted_sum(layer_inputs, node_data['weights'], node_data['bias']))
            layer_outputs.append(np.around(node_output[0], decimals=4))
            
        if layer != 'output':
            print('The outputs of the nodes in hidden layer number {} is {}'.format(layer.split('_')[1], layer_outputs))
    
        layer_inputs = layer_outputs # set the output of this layer to be the input to next layer

    network_predictions = layer_outputs
    return network_predictions

In [33]:
predictions = forward_propagate(small_network, inputs)
print('The predicted value by the network for the given input is {}'.format(np.around(predictions[0], decimals=4)))

The outputs of the nodes in hidden layer number 1 is [0.8323, 0.8268, 0.7735]
The outputs of the nodes in hidden layer number 2 is [0.7932, 0.8991]
The outputs of the nodes in hidden layer number 3 is [0.8232, 0.8924, 0.8141]
The predicted value by the network for the given input is 0.9112
